version: "{build}"

image:
- Visual Studio 2017

clone_folder: c:\gopath\src\github.com\Azure\acr-builder

stack: go 1.10

environment:
  GOPATH: c:\gopath

install:
  - set Path=c:\go\bin;c:\gopath\bin;
  - go version
  - go env

build: false
deploy: false

test_script:
  - go build github.com/Azure/acr-builder
  - go test ./...